name: Build EXE

on:
  workflow_dispatch:  # 允许手动点击运行

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pyinstaller pandas openpyxl

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name="GSM-ALUMINI" wechat_analyzer.py

      - name: Upload artifact (EXE file)
        uses: actions/upload-artifact@v4
        with:
          name: GSM-ANALYSIS_exe
          path: dist/
